### ISSUE TITLE
Create wallet overview screen

### ISSUE THREAD

**Issue by koshikraj** [safient/wallet#6]
## Description:

Create wallet overview screen

## Design: 

https://www.figma.com/file/0pLW8sjlRJJHiMK5MvWObX/Safient-Designs?node-id=3204%3A3094
![Wallet Overview (1)](https://user-images.githubusercontent.com/4023530/154939531-ad51896c-cec0-48fe-9e58-33092be883d7.png)

**Comment by Koushith** [comment]
Merged with main,
